/**
 * PM2 — prod Adixon (user :8000, admin :8001 sous /studio).
 *
 * watch = redémarrage auto si le backend Python change après un deploy/rsync.
 * static/templates : pas de watch (cache-bust front suffit, évite restarts inutiles).
 */
module.exports = {
  apps: [
    {
      name: "rod-ia-user",
      cwd: "/var/www/rod-ia",
      script: "run_user.py",
      interpreter: "/var/www/rod-ia/.venv/bin/python",
      args: "--host 127.0.0.1 --port 8000",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 40,
      min_uptime: "5s",
      max_memory_restart: "700M",
      // Redémarre si .py backend change (deploy / édition)
      watch: ["src/accor", "run_user.py"],
      ignore_watch: [
        "node_modules",
        "data",
        "models",
        "static",
        "templates",
        ".venv",
        "__pycache__",
        "*.pyc",
        "*.log",
        "RELEASE.txt",
      ],
      watch_delay: 1500,
      env: {
        ACCOR_HOST: "127.0.0.1",
        ACCOR_PORT: "8000",
        ACCOR_RELOAD: "0",
        PYTHONUNBUFFERED: "1",
      },
      out_file: "/var/log/rod-ia/user.out.log",
      error_file: "/var/log/rod-ia/user.error.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "rod-ia-admin",
      cwd: "/var/www/rod-ia",
      script: "run_admin.py",
      interpreter: "/var/www/rod-ia/.venv/bin/python",
      args: "--host 127.0.0.1 --port 8001",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 40,
      min_uptime: "5s",
      max_memory_restart: "900M",
      watch: ["src/accor", "run_admin.py"],
      ignore_watch: [
        "node_modules",
        "data",
        "models",
        "static",
        "templates",
        ".venv",
        "__pycache__",
        "*.pyc",
        "*.log",
        "RELEASE.txt",
      ],
      watch_delay: 1500,
      env: {
        ACCOR_HOST: "127.0.0.1",
        ACCOR_PORT: "8001",
        ACCOR_URL_PREFIX: "/studio",
        ACCOR_RELOAD: "0",
        PYTHONUNBUFFERED: "1",
      },
      out_file: "/var/log/rod-ia/admin.out.log",
      error_file: "/var/log/rod-ia/admin.error.log",
      merge_logs: true,
      time: true,
    },
  ],
};
