df_sales:
  type: dataframe
  requires: []
  file: data/hotel_sales_raw_extended_data.xlsx

t_sales:
  type: table
  requires: [df_sales]
  sql: |
    SELECT
        *
    FROM
        df_sales

t_hotel_codes:
  type: table
  requires: 
    - t_sales
  sql: |
    SELECT DISTINCT
        HOTEL_CODE
    FROM
        t_sales
    ORDER BY
        HOTEL_CODE

t_types:
  type: table
  requires: 
    - t_sales
  sql: |
    SELECT DISTINCT
        TYPE
    FROM
        t_sales
    ORDER BY
        TYPE


t_gammes:
  type: table
  requires: 
    - t_sales
  sql: |
    SELECT DISTINCT
        GAMME
    FROM
        t_sales
    ORDER BY
        GAMME


t_natures:
  type: table
  requires: 
    - t_sales
  sql: |
    SELECT DISTINCT
        NATURE
    FROM
        t_sales
    ORDER BY
        NATURE


t_machines:
  type: table
  requires: 
    - t_sales
  sql: |
    SELECT DISTINCT
        MACHINE
    FROM
        t_sales
    ORDER BY
        MACHINE


t_marques:
  type: table
  requires: 
    - t_sales
  sql: |
    SELECT DISTINCT
        MARQUE
    FROM
        t_sales
    ORDER BY
        MARQUE


t_fournisseurs:
  type: table
  requires: 
    - t_sales
  sql: |
    SELECT DISTINCT
        FOURNISSEUR
    FROM
        t_sales
    ORDER BY
        FOURNISSEUR


t_categories:
  type: table
  requires: 
    - t_sales
  sql: |
    SELECT DISTINCT
        CATEGORIE
    FROM
        t_sales
    ORDER BY
        CATEGORIE

